version: "3.8"

services:
  user_service:
    build: ./user-service
    depends_on:
      - "dbuser"

  post_service:
    build: ./post-service
    depends_on:
      - "dbpost"

  api:
    build: ./api  
    depends_on:
      -  "redisdb"
      -  "user_service"
      -  "post_service"
      
  

  dbpost:
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=postdb
      - POSTGRES_USER=hatsker
      - POSTGRES_PASSWORD=1
    ports: 
      - "5433:5433"
    volumes:
      - ./database/post.sql:docker-entrypoint-initdb.d/create_tables.sql
  dbuser:
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=users
      - POSTGRES_USER=hatsker
      - POSTGRES_PASSWORD=1
    ports: 
      - "5434:5434"
    volumes:
      - ./database/user.sql:docker-entrypoint-initdb.d/create_tables.sql
  redisdb:
    image:  redis
    ports:
      - "6378:6378"


      